name: Build Exploit AArch64 Android

# 触发条件：push代码、手动点击运行
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y wget unzip make

      - name: 下载 Android NDK r25c
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "$PWD/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: 编译 aarch64 静态二进制
        run: |
          # 编译器：aarch64-linux-android30-clang 适配安卓11
          CC=aarch64-linux-android30-clang
          $CC exp.c -o exp_arm64 -static -lpthread -O2

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: exploit-bin
          path: exp_arm64
